### ISSUE TITLE
typo in rdf serialisation

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/ADMS#4]
In the RDF serialization there is adms:schemeAgency defined, while in the html there is adms:schemaAgency.
The difference is in the character 'e' and 'a'.

The html will be followed and thus the RDF serialization is adapted.

**Comment by csnyulas** [comment]
As we discussed in the ADMS Seminar on 4/25, the recommendation was to do the following changes in the RDF serialization:
- on `adms:schemeAgency` set `owl:deprecated true` , and 
- make the two properties properties equivalent, i.e. `adms:schemeAgency owl:equivalentProperty adms:schemaAgency`.

Besides these two actions, I would also recommend to add the statement:
      `adms:schemeAgency dcterms:isReplacedBy adms:schemaAgency`.

The HTML serialization, which was already referring to `adms:schemaAgency`, should remain unchanged (i.e. no need to do any reference to the `adms:schemeAgency` property, which is now deprecated).
